apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-microservice
  labels:
    app: go-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-microservice
  template:
    metadata:
      labels:
        app: go-microservice
    spec:
      containers:
      - name: go-microservice
        image: iBro34/go-microservice:latest  # Replace with your Docker image
        ports:
        - containerPort: 8080
        env:
        - name: PUBSUB_EMULATOR_HOST
          value: "pubsub-emulator-service:8085"
        - name: PUBSUB_PROJECT_ID
          value: "sample"
---
apiVersion: v1
kind: Service
metadata:
  name: go-microservice-service
spec:
  selector:
    app: go-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
