# Use the Google Cloud SDK base image
FROM google/cloud-sdk:latest

# Install Pub/Sub Emulator
RUN gcloud components install pubsub-emulator

# Expose the default port for the Pub/Sub Emulator
EXPOSE 8085

# Start the Pub/Sub Emulator
CMD ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port=0.0.0.0:8085"]
