name: Go CI

# Run this workflow on every push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Go environment
    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    # Step 3: Cache Go modules to improve build times
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Step 4: Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Step 5: Run tests (unit and integration tests)
    - name: Run tests
      run: go test ./... -v

  # Optional: Docker build and push
  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Build Docker image
    - name: Build Docker image
      run: docker build -t your-dockerhub-username/go-microservice:latest .

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Push Docker image
    - name: Push Docker image
      run: docker push your-dockerhub-username/go-microservice:latest
